### ISSUE TITLE
Simplification: Use the main element

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#270]
@gewoonderrik stumbled upon this: http://html5doctor.com/the-main-element/

Maybe we could use it instead of `#main` or `#content`. What do you guys think?

**Comment by haroldangenent** [comment]
@gewoonderrik Could you update us about this?

**Comment by haroldangenent** [comment]
@gewoonderrik will update us today.

**Comment by gewoonderrik** [comment]
Update: Yes we should use the main element within TrendPress. It's supported in all modern browsers. Main should contain the main content of our websites. Rule of thumb is that content used within the main element should be unique per page. `<section id="main">` should be replaced with just a `<main>`. It doesn't need any class or id because it's a unique element anyway.

More info on the matter: 

* http://www.w3schools.com/tags/tag_main.asp
* http://blog.teamtreehouse.com/use-html5-sectioning-elements
* http://caniuse.com/#feat=html5semantic < support

**Comment by haroldangenent** [comment]
Let's do it.

**Comment by gewoonderrik** [comment]
Done. Please review!

**Comment by haroldangenent** [comment]
Nice!
