### ISSUE TITLE
Padding and margin madness

### ISSUE THREAD

**Issue by sboerrigter** [trendwerk/trendpress#283]
Elements are devided by margins and paddings, but sometimes it doesn't look logical. See the screenshot below for an example. The content is pushed down by multiple margins and paddings ons different elements. Why is this so complex?

![screen shot 2014-07-11 at 15 25 24](https://cloud.githubusercontent.com/assets/786875/3553168/b1d6db48-0900-11e4-812c-d8fff80c0517.png)

**Comment by gewoonderrik** [comment]
@sboerrigter: I've reduced most of the 'margin and padding madness'. 

A few notes:

* Why is the <p> tag around the author info div? - There isn't any but it looks like there is because the `<p>` doesn't have a `float: left;` or `clear: both;`. 
* The comment section has three different div's with all have margins. Why? - I guess I've fixed this. But I'm not exactly sure. Can you have a look at it. I couldn't find more that two `<div>` elements.

In my defence; adding some padding can be handy sometimes. You don't want to overwrite the elements margin (especially if it's a grid-like element like `@include column-4` for example). So if you need some extra spacing padding is quite useful.

I hope the current situation is more to your liking.
