### ISSUE TITLE
Search styling

### ISSUE THREAD

**Issue by luukdv** [trendwerk/trendpress#382]
Right now, there's styling declared for search forms in about 4 or 5 files/places. Maybe we should declare this in one place and extend it everywhere.

**Comment by gewoonderrik** [comment]
I've removed most of the declarations. Now there's only the `.search` declaration on line 271 of `_parts.scss` and little tweak in `_widgets.scss` on line 342. I've also renamed `.search` to `.search-form` because search pages already get the `.search` class as a body class (which is confusing). I hope everyone's on board with this. It seemed like the right thing to do. Please review and close.

**Comment by gewoonderrik** [comment]
@luukdv @haroldangenent Could you guys have a look at this?
