### ISSUE TITLE
Button styling

### ISSUE THREAD

**Issue by luukdv** [trendwerk/trendpress#383]
I'm noticing that a lot of times the styling of submit buttons, buttons in widgets and primary call to action buttons differ, when this is intented to be the same. Maybe we should just extend the the primary CTA class in all these cases. I know browsers render submit buttons differently, so we should pay attention to specific declarations to override this.

**Comment by gewoonderrik** [comment]
I've made an extend for this called `.button-style`. Seemed like a good semantical name. Does everyone agree with this?

In `_typography.scss` I've added the extend to the global button style. The class `.secondary` builds on top of it. In `_forms.scss` `.button-style` is applied to `input[type="submit"], input[type="button"], input[type="reset"], button`. Some remaining rules are left because of cross browser/platform consistency.

**Comment by sboerrigter** [comment]
Why not just .button? Everything is a style since it's a stylesheet right ?

**Comment by gewoonderrik** [comment]
We're already using `.button` for our call to actions.

**Comment by haroldangenent** [comment]
I agree with @sboerrigter. I don't think any `-style` declaration is semantical. The rest of the commit seems nice and clean to me.

We should use `.button` for this and remove the declaration of `.button` in `typography.scss`.

**Comment by gewoonderrik** [comment]
Done. Please review!

**Comment by haroldangenent** [comment]
Looks good. I was doubting this, but it's actually pretty good that `&.secondary` is inside the actual extend. This makes sure that you can also have secondary buttons in the case of `input[type="submit"]`.
