### ISSUE TITLE
FontAwesome icons on android 1.1 - 4.3

### ISSUE THREAD

**Issue by luukdv** [trendwerk/trendpress#421]
Android's browser doesn't seem to display FontAwesome glyphs we use for icons (like mobile navigation - see screenshot).

![screen shot 2015-04-22 at 15 59 51](https://cloud.githubusercontent.com/assets/5585947/7276426/c57cc1d2-e909-11e4-9acf-a32e1c05548b.png)

On 4.4 and upwards this is supported, but older versions are missing out. This is still more than 50%, so we should investigate if this is fixable or if we should include a fallback.

![screen shot 2015-04-22 at 16 05 09](https://cloud.githubusercontent.com/assets/5585947/7276430/caca939e-e909-11e4-8bc2-a7ee12598ab6.png)

**Comment by haroldangenent** [comment]
@luukdv will remove Font Awesome in favor of four lines.

**Comment by haroldangenent** [comment]
@luukdv 

- Why did you pick this menu icon animation? I liked the twirly one on the left ;-)
- I don't really like the search icon animation, since it doesn't represent it's state (doesnt seem active).
- Search icon bugs in Firefox, see first screenshot
- I get a horizontal scrollbar in Firefox (seems like the same issue), see second screenshot

![schermafbeelding 2015-05-15 om 16 03 29](https://cloud.githubusercontent.com/assets/1481468/7654314/7a490afc-fb1c-11e4-9550-21ee02373570.png)
![schermafbeelding 2015-05-15 om 16 03 54](https://cloud.githubusercontent.com/assets/1481468/7654315/7a4aede0-fb1c-11e4-80cd-de9bc6995121.png)

**Comment by luukdv** [comment]
Updated.

**Comment by haroldangenent** [comment]
Looks good.
