### ISSUE TITLE
Question: Video container styling

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#528]
```
.video-container {
  height: 0;
  margin-bottom: 30px;
  padding-top: 30px;
  padding-bottom: 56.25%;
  position: relative;
```

I was wondering about these declarations. 

- How is the `padding-bottom` calculated?
- Could we use `$line-height` for the `30px` things? I suppose this is done to mimic a paragraph
- Why _margin_ on the bottom but _padding_ on top?

**Comment by luukdv** [comment]
* `padding-bottom` is the percentage ratio of 16:9
* `margin-bottom` is added for when the container is not wrapped in a paragraph
* I never understood the added value of `padding-top` (it's adding height to the video area itself), but since everyone is applying it (even Chris Coyier) I guess there's a good reason

**Comment by luukdv** [comment]
I got interested and searched for the reason, it's a fix for IE5-IE6 and everyone is just copying the code. Let's remove it

**Comment by haroldangenent** [comment]
Remove what part? The `padding-top`?

**Comment by luukdv** [comment]
Yes.

**Comment by gewoonderrik** [comment]
The padding has been removed. Seems to work just fine without it. Please review!

**Comment by haroldangenent** [comment]
Yes. Kitten mittens are still perfectly visible without the padding.
