### ISSUE TITLE
Simplification: Table

### ISSUE THREAD

**Issue by gewoonderrik** [trendwerk/trendpress#548]
What happens if we remove all the `border-bottom`, `border-right` etc. from `_tables.scss`? Maybe we should only define the `border-color` in `table`. Another simplification?

**Comment by luukdv** [comment]
I think I agree. Maybe we can improve our table styling even further to support mobile-first. I like these techniques: http://dbushell.com/demos/tables/rt_05-01-12.html & https://css-tricks.com/examples/ResponsiveTables/responsive.php, especially the one by David Bushell. Bootstrap has implemented a similar technique: http://getbootstrap.com/css/#tables-responsive.

**Comment by luukdv** [comment]
Move this one to components and close here?

**Comment by haroldangenent** [comment]
I don't agree, tables should be part of TrendPress.

**Comment by luukdv** [comment]
You're right.

**Comment by sboerrigter** [comment]
Also see: https://github.com/trendwerk/trendpress/commit/90ffaf5819329ba24e0d45dc681941a5a203d461

**Comment by luukdv** [comment]
Nice improvement. I think a slightly gray background for even rows look good and are a helpful visual cue. Shall we add this?

Furthermore, in the responsive-table example from Bootstrap there's an outer wrapper which adds a border:

![screen shot 2016-09-29 at 17 01 28](https://cloud.githubusercontent.com/assets/5585947/18959423/66992d4e-8666-11e6-981e-7ec997a0021f.png)

In TrendPress this is not the case:

![screen shot 2016-09-29 at 17 01 56](https://cloud.githubusercontent.com/assets/5585947/18959444/7c30d44a-8666-11e6-9a34-1432574361f5.png)

The problem is, users can add tables in the editor. Do we want to look at an output replacement function / JS solution or leave it this way?

**Comment by haroldangenent** [comment]
Leaving it this way is fine by me. Tables are hardly ever used.

**Comment by luukdv** [comment]
Agreed. @sboerrigter?

**Comment by luukdv** [comment]
Nice.
