### ISSUE TITLE
Auto include 7/1 pattern files to main

### ISSUE THREAD

**Issue by sboerrigter** [trendwerk/trendpress#555]
We should research this

**Comment by gewoonderrik** [comment]
There's a thing called [Globbing](https://github.com/chriseppstein/sass-globbing) which was invented by one of the creators of Compass. Since we're not using Compass this isn't very useful for us but fortunately someone made a [Gulp plug-in](https://www.npmjs.com/package/gulp-css-globbing) inspired by it. We should check this out!

**Comment by haroldangenent** [comment]
Awesome.

**Comment by luukdv** [comment]
Nice! One thing, why didn't you use camelcase in the gulpfile? And changed the camelcasing for base64, which is not even related to this issue? Can you fix this?

**Comment by sboerrigter** [comment]
There were more non-camecase variables then camelcase variables. I've changed 'cssBase64' to make it more consistent with the rest.

I have changed everything to camelcase now.
