### ISSUE TITLE
No sourcemaps in production

### ISSUE THREAD

**Issue by luukdv** [trendwerk/trendpress#561]
We should add the option to pass a `--production` flag to Gulp, on which there are no sourcemap references generated.

**Comment by luukdv** [comment]
Suggestion:

```
util = require('gulp-util')

// Write sourcemaps (not for production environment)
.pipe(util.env.production ? util.noop() : sourcemaps.write('.'))
```

`gulp --production`

**Comment by sboerrigter** [comment]
Why?

**Comment by luukdv** [comment]
Performance (saving a HTTP request)

**Comment by haroldangenent** [comment]
I thought sourcemaps only loaded when you use Inspector. I'm not sure. Most users don't have Inspector turned on.

If we'd use a flag for the environment, when would you use it? Before every commit? We would need a CI tool to run build scripts properly.

**Comment by luukdv** [comment]
Not sure too, but I remember a while ago we got some 404's when sourcemaps weren't available - which I want to avoid.

For when to use, I was thinking before a 'final' commit (before pushing changes to production). Automating this sounds good, but maybe that's another issue

**Comment by gewoonderrik** [comment]
Source maps are not treated as a normal HTTP request, so they're not bad for performance (just tested this in Chrome Inspector). Actually, they're made specifically for production, because this is where you should use concatted and minified files (a lot of people don't do this on local or staging environments).

Marking this as wontfix.
