### ISSUE TITLE
Box-link height

### ISSUE THREAD

**Issue by luukdv** [trendwerk/trendpress#567]
You can define a height in the map (I like it), but the calculation is:

`((height - $vertical-spacing) / 2)`. If `height` is defined as 50px and `$vertical-spacing` is 30px for example, you don't end up with a height of 50px. Maybe rename the argument.

**Comment by haroldangenent** [comment]
I'm not sure if I understand correctly. Just tested a boxed link, and it was exactly the right height. The height parameter is the right name in my opinion, since it actually calculates how to get the proper height.

However, the `$vertical-spacing` variable should probably be replaced by the `$line-height` variable, since that's more semantically correct.

This would be buggy when the `$vertical-spacing` (or `$line-height`) variable is larger than the requested height, since that would be impossible. Should we create an exception for that specific situation?
