### ISSUE TITLE
Galleries: Use "large" images instead of "full size"

### ISSUE THREAD

**Issue by sboerrigter** [trendwerk/trendpress#606]

**Comment by sboerrigter** [comment]
Images are now too big.

![screen shot 2016-03-17 at 16 02 56](https://cloud.githubusercontent.com/assets/786875/13850580/d6a60e0a-ec5a-11e5-8722-53e074d3b0c7.png)

**Comment by sboerrigter** [comment]
Also for images linking to the bigger size.

**Comment by luukdv** [comment]
Fancybox in general.

**Comment by sboerrigter** [comment]
Some possible sollutions:

* http://wordpress.stackexchange.com/questions/16809/add-filter-example-for-wp-get-attachment-link 
* https://oikos.digital/2011/09/tech-notes-using-resized-images-in-wordpress-galleries-and-lightboxes/

**Comment by haroldangenent** [comment]
I'm not a fan of these approaches.

- The filters do more than just what we want them to do;
- The Oikos approach uses `preg_replace`;
- We need quite some code to properly do this, if possible.

I believe this is not imported enough for these kind of solutions. They simply do not belong in a theme.

Since TrendPress is a WordPress theme, it should conform to WordPress' behaviour and use it's options to specify how the theme is implemented. Since this is not an option or default filter, I don't believe this is something a theme should do.

Therefore, I would say this is a `wontfix`.

**Comment by sboerrigter** [comment]
Ok, `wontfix`
