### ISSUE TITLE
IE compatibility mode edge

### ISSUE THREAD

**Issue by gewoonderrik** [trendwerk/trendpress#607]
Example: `<meta http-equiv="X-UA-Compatible" content="IE=Edge">`

Should we add this feature? It's often suggested (for example by the [Code Guide](http://codeguide.co/)) and it enables Internet Explorer to use the edge rendering mode, which is good (especially for older versions of Internet Explorer).

Thoughts?

**Comment by luukdv** [comment]
For which versions is this? I don't mind if the website is broken < IE9.

**Comment by sboerrigter** [comment]
> Edge mode tells Internet Explorer to display content in the highest mode available. With Internet Explorer 9, this is equivalent to IE9 mode. If a future release of Internet Explorer supported a higher compatibility mode, pages set to edge mode would appear in the highest mode supported by that version...

> ...Starting with IE11, edge mode is the preferred document mode … Use the HTML5 document type declaration to enable edge mode: <!doctype html>...

> ...Starting with IE11, document modes are deprecated and should no longer be used…

Source: http://stackoverflow.com/a/6771584

As I understand it edge mode is only supported by IE10+, but is no longer needed in IE11, because edge mode is declared automatically if the page is written in HTML 5. So the edge mode meta tag is only necessary for IE10.

Only < 0,5% of users are using IE10 (source: http://caniuse.com/usage-table), so I don't think it's worth it to add this.

**Comment by luukdv** [comment]
Good research. Shall we close this? Besides the reasons stated above, I don't really want to add extra code to help IE users.

**Comment by luukdv** [comment]
I'm closing this.
