### ISSUE TITLE
Drop pingback support

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#701]
```
<link rel="pingback" href="{{ site.pingback_url }}">
```

Taken from `header.twig`. Not sure about the consequences when removing this, but it seems a little used feature.

**Comment by luukdv** [comment]
Did some reading and I think it's a good idea to disable it by default. The average client often doesn't understand the function and sometimes asks about it, if they'd request this feature we can always turn it back on.

Interesting (though wouldn't work since XMLRPC is disabled): https://blog.sucuri.net/2014/03/more-than-162000-wordpress-sites-used-for-distributed-denial-of-service-attack.html
