### ISSUE TITLE
Remove tags from single post

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#725]
Like the title says. Drop support for tags in our theme.

**Comment by sboerrigter** [comment]
Why? This makes us less efficient.

**Comment by luukdv** [comment]
@sboerrigter Why? We could create a starter for this, and clutter the theme a little less. This makes development faster.

**Comment by haroldangenent** [comment]
@sboerrigter No, we spend time removing this and the styling for almost every website.

**Comment by sboerrigter** [comment]
*tag() mixin*
The mixin `tag()` is now only used in `_comment-respond.scss`. Shall we remove this mixin and move the code to that file?

*Tags in back-end*
Maybe we should also remove tags from the back-end since we don't support them anymore. Shall I do that?

*Starter for tags*
@luukdv suggested to create a starter for tags. Can I add this to a backlog somewhere?

**Comment by haroldangenent** [comment]
> Shall we remove this mixin and move the code to that file?

Yes, I see you've already done this.

> Tags in back-end

At first sight, this seems like it would take a lot of code and would get messy. I'm fine with leaving it in de back-end. The theme just doesn't support all possible WordPress options. Also doesn't seem worth it, since generally the `post` post type is not used.

> Starter

I've put it on the list.
